services:

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker , controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LOG_DIRS: /tmp/kraft-combined-logs
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_CLUSTER_ID: "TaVJLPKiRjqN2o7LXzMq2g"
    ports:
      - "9092:9092"


  postgres-users:
    image : postgres:15
    container_name : postgres_users
    environment:
      POSTGRES_DB: usersdb
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
    ports:
      - "5433:5432"


  postgres-accounts:
    image: postgres:15
    container_name: postgres-accounts
    environment:
      POSTGRES_DB: accountsdb
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
    ports:
      - "5434:5432"

  postgres-transactions:
    image: postgres:15
    container_name: postgres-transactions
    environment:
      POSTGRES_DB: txdb
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
    ports:
      - "5435:5432"



